name: Run Server Tests

on: [pull_request, workflow_dispatch]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: golang:1.23-alpine
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_PASSWORD: root
          POSTGRES_DB: seatsurfing_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Install server dependencies
      working-directory: ./server
      run: go get -d -v ./...
    - name: Run util tests
      working-directory: ./server/util/test
      run: go test -cover -v
      env:
        POSTGRES_URL: postgres://postgres:root@postgres/seatsurfing_test?sslmode=disable
        CGO_ENABLED: 0
    - name: Run repository tests
      working-directory: ./server/repository/test
      run: go test -cover -v
      env:
        POSTGRES_URL: postgres://postgres:root@postgres/seatsurfing_test?sslmode=disable
        CGO_ENABLED: 0
    - name: Run router tests
      working-directory: ./server/router/test
      run: go test -cover -v
      env:
        POSTGRES_URL: postgres://postgres:root@postgres/seatsurfing_test?sslmode=disable
        CGO_ENABLED: 0
